#!/usr/bin/env bash
#
# Regenerate the end-of-support table embedded in vps-audit.sh from
# https://endoflife.date (Ubuntu and Debian: the two distributions whose
# /etc/os-release has no SUPPORT_END field).
#
#   tools/update-eol-table.sh           rewrite the table in place
#   tools/update-eol-table.sh --check   exit 1 if the embedded table is stale
#
# Needs curl and jq. Run it when preparing a release; CI runs --check weekly.
#
# Per endoflife.date the two vendors use different fields, normalised here to
# "standard end" (free security support) and "extended end" (after which
# nothing is published): Ubuntu = eol / extendedSupport (ESM, needs Ubuntu Pro);
# Debian = support (security team) / eol (LTS).

set -o pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET="$REPO_DIR/vps-audit.sh"
API="https://endoflife.date/api"

fetch() {
    curl -fsSL --max-time 30 "$API/$1.json"
}

generate() {
    {
        fetch ubuntu | jq -r '.[]
            | select(.cycle | test("^(1[6-9]|2[0-9])\\."))
            | "ubuntu:\(.cycle)|\(.eol)|\(if (.extendedSupport == false or .extendedSupport == null) then .eol else .extendedSupport end)"'
        fetch debian | jq -r '.[]
            | select((.cycle | tonumber) >= 9)
            | "debian:\(.cycle)|\(.support)|\(.eol)"'
    } | sort -t'|' -k1,1V | sed 's/^/    "/; s/$/"/'
}

main() {
    local table block
    table="$(generate)" || {
        echo "could not fetch lifecycle data" >&2
        exit 2
    }
    [[ -n "$table" ]] || {
        echo "empty lifecycle data" >&2
        exit 2
    }
    block="$(printf '%s\n' "# BEGIN EOL TABLE (generated by tools/update-eol-table.sh)" \
        "readonly -a EOL_TABLE=(" "$table" ")" "# END EOL TABLE")"

    local current
    current="$(sed -n '/^# BEGIN EOL TABLE/,/^# END EOL TABLE/p' "$TARGET")"

    if [[ "${1:-}" == "--check" ]]; then
        if [[ "$current" == "$block" ]]; then
            echo "EOL table is current."
            exit 0
        fi
        echo "EOL table is stale. Run tools/update-eol-table.sh and commit the result." >&2
        diff <(printf '%s\n' "$current") <(printf '%s\n' "$block") >&2
        exit 1
    fi

    local tmp
    tmp="$(mktemp)"
    awk -v block="$block" '
        /^# BEGIN EOL TABLE/ { print block; skip = 1; next }
        /^# END EOL TABLE/   { skip = 0; next }
        !skip                { print }
    ' "$TARGET" >"$tmp" && cat "$tmp" >|"$TARGET"
    rm -f "$tmp"
    echo "Updated the EOL table in vps-audit.sh ($(printf '%s\n' "$table" | wc -l) entries)."
}

main "$@"
